# Generated by Django 5.1.5 on 2025-02-10 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="description",
        ),
        migrations.RemoveField(
            model_name="menu",
            name="dish_name",
        ),
        migrations.RemoveField(
            model_name="menu",
            name="ingredients",
        ),
        migrations.AddField(
            model_name="menu",
            name="image",
            field=models.ImageField(
                default="menu_images/default.jpg", upload_to="menu_images/"
            ),
        ),
        migrations.AddField(
            model_name="menu",
            name="name",
            field=models.CharField(default="Dish Name", max_length=100),
        ),
        migrations.AddField(
            model_name="menu",
            name="price",
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="menu",
            name="quantity",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="menu",
            name="category",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menus",
                to="management.category",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="menu",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="menu",
            name="discount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="unit",
            field=models.CharField(max_length=50),
        ),
    ]
