# Generated by Django 5.1.5 on 2025-02-13 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "management",
            "0002_remove_category_description_remove_menu_dish_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventplan",
            name="menu_items",
            field=models.ManyToManyField(blank=True, to="management.menu"),
        ),
    ]
