# Generated by Django 5.1.5 on 2025-02-25 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0006_remove_orderitem_menu_variant_orderitem_menu"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="preorder",
            name="menu_variant",
        ),
        migrations.AddField(
            model_name="preorder",
            name="menu",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="management.menu",
            ),
            preserve_default=False,
        ),
    ]
