# Generated by Django 5.1.5 on 2025-02-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0007_remove_preorder_menu_variant_preorder_menu"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventplan",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("marriage", "Marriage"),
                    ("birthday", "Birthday"),
                    ("reception", "Reception"),
                    ("others", "Others"),
                ],
                default="others",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="eventplan",
            name="other_event_type",
            field=models.CharField(
                blank=True, help_text="Specify if event type is others", max_length=255
            ),
        ),
    ]
