# Generated by Django 5.1.5 on 2025-03-05 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0008_eventplan_event_type_eventplan_other_event_type"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Ingredient",
            new_name="Inventory",
        ),
        migrations.AddField(
            model_name="menu",
            name="inventory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="management.inventory",
            ),
        ),
        migrations.DeleteModel(
            name="MenuIngredient",
        ),
    ]
