# Generated by Django 5.1.5 on 2025-03-05 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0009_rename_ingredient_inventory_menu_inventory_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menu",
            name="quantity",
        ),
    ]
