# Generated by Django 5.1.5 on 2025-03-05 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0010_remove_menu_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventory",
            name="name",
        ),
        migrations.RemoveField(
            model_name="menu",
            name="inventory",
        ),
        migrations.AddField(
            model_name="inventory",
            name="menu",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="management.menu",
            ),
            preserve_default=False,
        ),
    ]
