# Generated by Django 5.1.5 on 2025-03-07 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0011_remove_inventory_name_remove_menu_inventory_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="catering",
            name="advance_amount",
        ),
        migrations.RemoveField(
            model_name="catering",
            name="event_type",
        ),
    ]
