# Generated by Django 5.1.5 on 2025-03-07 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0013_catering_custom_option"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventplan",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "Planned"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="planned",
                max_length=20,
            ),
        ),
    ]
