# Generated by Django 5.1.5 on 2025-03-07 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0015_alter_order_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="inventory",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menu_inventory",
                to="management.inventory",
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="menu",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory_detail",
                to="management.menu",
            ),
        ),
    ]
