# Generated by Django 5.1.5 on 2025-03-09 06:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0016_menu_inventory_alter_inventory_menu"),
    ]

    operations = [
        migrations.AddField(
            model_name="tablereservation",
            name="date_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
