# Generated by Django 5.1.5 on 2025-03-09 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0018_remove_menu_inventory_alter_inventory_menu"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="expiry_date",
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="inventory",
            name="original_quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="quantity",
            field=models.IntegerField(),
        ),
    ]
